### ISSUE TITLE
What's a kmt microservice?

### ISSUE THREAD

**Issue by adambraimbridge** [Financial-Times/kmt-utilities#17]
What's a kmt microservice? What does KMT stand for?

**Comment by ciprianlujeru** [comment]
It was the initial name of our app `Knowledge Manager Tools` but it was renamed to `Knowledge & Administration Tools`

**Comment by adambraimbridge** [comment]
Thanks. I created https://github.com/Financial-Times/kmt-utilities/pull/18/files for this
